name: 'reddit_ads_integration_tests'
version: '0.7.0'
profile: 'integration_tests'
config-version: 2

vars: 
  reddit_ads_schema: reddit_ads_integration_tests_4
  reddit_ads_account_identifier: "reddit_ads_account_data"
  reddit_ads_business_account_identifier: "reddit_ads_business_account_data"
  reddit_ads_account_report_identifier: "reddit_ads_account_report_data"
  reddit_ads_account_conversions_report_identifier: "reddit_ads_account_conversions"
  reddit_ads_ad_identifier: "reddit_ads_ad_data"
  reddit_ads_ad_report_identifier: "reddit_ads_ad_report_data"
  reddit_ads_ad_conversions_report_identifier: "reddit_ads_ad_conversions"
  reddit_ads_ad_group_identifier: "reddit_ads_ad_group_data"
  reddit_ads_ad_group_report_identifier: "reddit_ads_ad_group_report_data"
  reddit_ads_ad_group_conversions_report_identifier: "reddit_ads_ad_group_conversions"
  reddit_ads_campaign_identifier: "reddit_ads_campaign_data"
  reddit_ads_campaign_report_identifier: "reddit_ads_campaign_report_data"
  reddit_ads_campaign_conversions_report_identifier: "reddit_ads_campaign_conversions"
  reddit_ads_campaign_country_report_identifier: "reddit_ads_campaign_country_report_data"
  reddit_ads_campaign_country_conversions_report_identifier: "reddit_ads_campaign_country_conversions_report_data"
  
  # Comment out when generating docs!
  reddit_ads__ad_conversions_passthrough_metrics: # @docs-ignore
    - name: 'view_through_conversion_attribution_window_week' # @docs-ignore
  reddit_ads__account_passthrough_metrics:  # @docs-ignore
    - name: conversions # @docs-ignore
    - name: app_install_metrics_install # @docs-ignore
      alias: installs # @docs-ignore
    - name: view_through_conversions # @docs-ignore
  reddit_ads__campaign_passthrough_metrics:  # @docs-ignore
    - name: conversions # @docs-ignore
    - name: app_install_metrics_install # @docs-ignore
      alias: installs # @docs-ignore
    - name: total_value # @docs-ignore
  reddit_ads__ad_group_passthrough_metrics: # @docs-ignore
    - name: conversions # @docs-ignore
    - name: app_install_metrics_install # @docs-ignore
      alias: installs # @docs-ignore
    - name: total_items # @docs-ignore
  reddit_ads__ad_passthrough_metrics: # @docs-ignore
    - name: conversions # @docs-ignore
    - name: app_install_metrics_install # @docs-ignore
      alias: installs # @docs-ignore
  reddit_ads__campaign_country_passthrough_metrics: # @docs-ignore
    - name: conversions2 # @docs-ignore
      transform_sql: "cast(conversions2 as bigint)" # @docs-ignore
  reddit_ads__campaign_country_conversions_passthrough_metrics: # @docs-ignore
    - name: app_install_metrics_install # @docs-ignore
      alias: installs2 # @docs-ignore
      transform_sql: "cast(installs2 as bigint)" # @docs-ignore

  # For validation testing
  reddit_ads__conversion_event_types:
    - 'lead'
    - 'purchase'
    - 'custom'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +schema: "reddit_ads_{{ var('directed_schema','dev') }}"

seeds:
  +docs:
    show: false
  reddit_ads_integration_tests:
    reddit_ads_account_conversions:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_account_data:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_account_report_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_conversions:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        ad_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_group_conversions:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_group_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_group_report_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_report_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        ad_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_business_account_data:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_conversions:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_country_conversions_report_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_country_report_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_report_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
flags:
  send_anonymous_usage_stats: False
  use_colors: True