name: 'reddit_ads_integration_tests'
version: '0.4.0'
profile: 'integration_tests'
config-version: 2

vars: 
  reddit_ads_schema: reddit_ads_integration_tests_4
  reddit_ads_account_identifier: "reddit_ads_account_data"
  reddit_ads_account_report_identifier: "reddit_ads_account_report_data"
  reddit_ads_account_conversions_report_identifier: "reddit_ads_account_conversions"
  reddit_ads_ad_identifier: "reddit_ads_ad_data"
  reddit_ads_ad_report_identifier: "reddit_ads_ad_report_data"
  reddit_ads_ad_conversions_report_identifier: "reddit_ads_ad_conversions"
  reddit_ads_ad_group_identifier: "reddit_ads_ad_group_data"
  reddit_ads_ad_group_report_identifier: "reddit_ads_ad_group_report_data"
  reddit_ads_ad_group_conversions_report_identifier: "reddit_ads_ad_group_conversions"
  reddit_ads_campaign_identifier: "reddit_ads_campaign_data"
  reddit_ads_campaign_report_identifier: "reddit_ads_campaign_report_data"
  reddit_ads_campaign_conversions_report_identifier: "reddit_ads_campaign_conversions"
  reddit_ads_campaign_country_report_identifier: "reddit_ads_campaign_country_report_data"
  reddit_ads_campaign_country_conversions_report_identifier: "reddit_ads_campaign_country_conversions_report_data"
  
  ## Disable when generating docs
  reddit_ads__ad_conversions_passthrough_metrics: 
    - name: 'view_through_conversion_attribution_window_week'
  reddit_ads__account_passthrough_metrics: 
    - name: conversions
    - name: app_install_metrics_install
      alias: installs
    - name: view_through_conversions
  reddit_ads__campaign_passthrough_metrics: 
    - name: conversions
    - name: app_install_metrics_install
      alias: installs
    - name: total_value
  reddit_ads__ad_group_passthrough_metrics:
    - name: conversions
    - name: app_install_metrics_install
      alias: installs
    - name: total_items
  reddit_ads__ad_passthrough_metrics:
    - name: conversions
    - name: app_install_metrics_install
      alias: installs
  reddit_ads__campaign_country_passthrough_metrics:
    - name: conversions2
      transform_sql: "cast(conversions2 as bigint)"
  reddit_ads__campaign_country_conversions_passthrough_metrics:
    - name: app_install_metrics_install
      alias: installs2
      transform_sql: "cast(installs2 as bigint)"

  # For validation testing
  reddit_ads__conversion_event_types:
    - 'lead'
    - 'purchase'
    - 'custom'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +schema: "reddit_ads_{{ var('directed_schema','dev') }}"

seeds:
  reddit_ads_integration_tests:
    +column_types:
      id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      ad_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      clicks: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      impressions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      spend: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      conversions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      view_through_conversions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      total_value: float
      total_items: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"