name: 'reddit_ads_integration_tests'
version: '0.3.0'
profile: 'integration_tests'
config-version: 2

vars: 
  reddit_ads_schema: reddit_ads_integration_tests_4
  reddit_ads_account_identifier: "reddit_ads_account_data"
  reddit_ads_account_report_identifier: "reddit_ads_account_report_data"
  reddit_ads_account_conversions_report_identifier: "reddit_ads_account_conversions"
  reddit_ads_ad_identifier: "reddit_ads_ad_data"
  reddit_ads_ad_report_identifier: "reddit_ads_ad_report_data"
  reddit_ads_ad_conversions_report_identifier: "reddit_ads_ad_conversions"
  reddit_ads_ad_group_identifier: "reddit_ads_ad_group_data"
  reddit_ads_ad_group_report_identifier: "reddit_ads_ad_group_report_data"
  reddit_ads_ad_group_conversions_report_identifier: "reddit_ads_ad_group_conversions"
  reddit_ads_campaign_identifier: "reddit_ads_campaign_data"
  reddit_ads_campaign_report_identifier: "reddit_ads_campaign_report_data"
  reddit_ads_campaign_conversions_report_identifier: "reddit_ads_campaign_conversions"
  
  reddit_ads__ad_conversions_passthrough_metrics: 
    - name: 'view_through_conversion_attribution_window_week'

  # For validation testing
  reddit_ads__conversion_event_types:
    - 'lead'
    - 'purchase'
    - 'custom'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +schema: "reddit_ads_{{ var('directed_schema','dev') }}"

seeds:
  reddit_ads_integration_tests:
    +column_types:
      id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      date: date
      clicks: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      impressions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      spend: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      conversions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      view_through_conversions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      total_value: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      total_items: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"