name: 'reddit_ads_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars: 
  reddit_ads_schema: reddit_ads_integration_tests_1
  reddit_ads_account_identifier: "reddit_ads_account_data"
  reddit_ads_account_report_identifier: "reddit_ads_account_report_data"
  reddit_ads_ad_identifier: "reddit_ads_ad_data"
  reddit_ads_ad_report_identifier: "reddit_ads_ad_report_data"
  reddit_ads_ad_group_identifier: "reddit_ads_ad_group_data"
  reddit_ads_ad_group_report_identifier: "reddit_ads_ad_group_report_data"
  reddit_ads_campaign_identifier: "reddit_ads_campaign_data"
  reddit_ads_campaign_report_identifier: "reddit_ads_campaign_report_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  reddit_ads_integration_tests:
    +column_types:
      id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
